# multi_model_raster.R
# make a multi-model raster from netCDF output results generated by gl_analysis.R

# Project: NASA HiMAT
# Danielle S Grogan
# last updated: 2019-07-24

multi_model_raster = function(res.dir.base,   # results directory from which to read, one level up from GCM names
                              gcm.list,       # list of gcm names, used to make directory path
                              file.nm,        # name of result netcdf file to read (e.g., "ET_pg_mmYr.nc")
                              rcp,            # one of: "historical", rcp45", "rcp85".  
                              out.dir         # directory to write output
                              ){   
  
  file.list = lapply(gcm.list, FUN = function(x) file.path(res.dir.base, x, rcp, file.nm))
  brk = do.call(stack, 
                lapply(file.list,
                       raster::brick))
  ids = rep(seq(1:(nlayers(brk)/length(gcm.list))), length(gcm.list))
  brk.mmm = stackApply(brk, 
                       indices = ids, 
                       fun = mean,
                       filename = file.path(out.dir, sub(".nc", paste("_", rcp, ".nc", sep=""), c(file.nm))),
                       overwrite = T)
  
}
  