# multi_model_df.R
# make a multi-model data frame from csv output results generated by gl_analysis.R

# Project: NASA HiMAT
# Danielle S Grogan
# last updated: 2019-07-23

multi_model_df = function(res.dir.base,   # results directory from which to read, one level up from GCM names
                          gcm.list,       # list of gcm names, used to make directory path
                          file.nm,        # name of result csv file to read (e.g., "Glacier_runoff_basins_km3Yr.csv")
                          years,          # sequence of years. INCLUDE HISTORICAL AND FUTURE
                          rcp,            # one of: "rcp45", "rcp85".  NO HISTORICAL - this function will build historical + rcp time series
                          basin,          # name of basin, or "Ex" for sum of all exorheic basins
                          out.dir         # directory to write output
                          ){       

  # create out.dir if it does not exist
  f1 = file.path(strsplit(out.dir, "/")[[1]][1], strsplit(out.dir, "/")[[1]][2])
  if(!file.exists(f1)){
    dir.create(f1)
  }
  if(!file.exists(out.dir)){
    dir.create(out.dir)
  }
  
  # make data frame with all GCM simulations for basin
  mmm.df = data.frame(matrix(nc = length(years), nr = length(gcm.list)))
  for(i in 1:length(gcm.list)){
    data.hist = read.csv(file.path(res.dir.base, gcm.list[i], "historical", file.nm))
    data.rcp  = read.csv(file.path(res.dir.base, gcm.list[i], rcp, file.nm))
    data.ts   = merge(data.hist, data.rcp)
    
    if(basin == "Ex"){
      mmm.df[i,] = colSums(data.ts[,2:ncol(data.ts)])
      basin.nm = "ExorheicAll"
    }else{
      mmm.df[i,] = data.ts[which(data.ts[,1] == basin), 2:ncol(data.ts)]
      basin.nm = basin
    }
  }
  
  # calculate mean
  multi.model.mean = colMeans(mmm.df)
  mmm.df = rbind(mmm.df, multi.model.mean)
  
  colnames(mmm.df) = years
  rownames(mmm.df) = c(gcm.list, "multi_model_mean")
  
  # write to file
  write.csv(mmm.df, file.path(out.dir, sub(".csv", paste("_", basin.nm, "_", rcp, ".csv", sep=""), c(file.nm))), row.names = T)
  
  # return data frame
  return(mmm.df)
}
